### ISSUE TITLE
plenv Removes Environment Variables

### ISSUE THREAD

**Issue by theory** [tokuhirom/plenv#99] opened 2015-09-22 18:55 UTC
I need to use DBD::Oracle, which requires that the `$ORACLE_HOME` and `$DYLD_LIBRARY_PATH` environment variables be set. However, plenv seems to wipe them out:

    DYLD_LIBRARY_PATH=/usr/local/instantclient_11_2 perl -E 'say $ENV{DYLD_LIBRARY_PATH}'
    

No output. Not the case when using a full path:

    DYLD_LIBRARY_PATH=/usr/local/instantclient_11_2 /Users/david/.plenv/versions/5.22.0/bin/perl -E 'say $ENV{DYLD_LIBRARY_PATH}'
    /usr/local/instantclient_11_2

So how do I get environment variables I set to be passed through the plenv shims so the Perl interpreter can see them?

**Comment by miyagawa** [comment] 2015-09-22 20:10
I cannot reproduce, and can't seem to find a code that does this kind of thing in plenv shims. What's the path to your `perl`, and if you run `perl -V` is there a thing that might override it, like something in `PERL5OPT`?

**Comment by theory** [comment] 2015-09-22 20:18
Path to Perl is `/Users/david/.plenv/versions/5.22.0/bin/perl`, symlinked to `/Users/david/perl5/perlbrew/perls/perl-5.22.0`. I'm using ZSH, not bash. Nothing in `perl -V` matches `LD`. `$PERL5OPT` is not set.

**Comment by miyagawa** [comment] 2015-09-22 20:19
wait, are you using plenv or perlbrew, or combination of both!?

**Comment by theory** [comment] 2015-09-22 20:25
I have been using perlbrew for a few years. Thought I'd try plenv, since other folks seem to prefer it, so used [Aristotle's symlink hack](http://blogs.perl.org/users/aristotle/2015/06/plenv-perlbrew-cuckoo.html) to use the existing perlbrew builds. After futzing with the above for a while, I shut off plenv and turned off perlbrew again, and now my variables are passed through again as expected.

**Comment by miyagawa** [comment] 2015-09-22 20:27
I have no idea how that actually works, but it has never occurred to me of using existing perlbrew as a plenv installation. Can we close this as not an issue?

**Closed** 2015-09-22 20:27 UTC

**Comment by theory** [comment] 2015-09-22 20:31
Here, I built 5.23.3 with plenv. Same issue:

    > plenv which perl
    /Users/david/.plenv/versions/5.23.3/bin/perl
    > DYLD_LIBRARY_PATH=/usr/local/instantclient_11_2 perl -E 'say $ENV{DYLD_LIBRARY_PATH}'
    

Not true of all variables, though:

    > BLAH=hi perl -E 'say $ENV{BLAH}'    
    hi

**Comment by miyagawa** [comment] 2015-09-22 20:32
That sounds like an OS issue? plenv shims runs the binary with `exec`, and your OS clears up when invoking another process?

**Comment by miyagawa** [comment] 2015-09-22 20:32
see: http://stackoverflow.com/questions/12064725/dyld-dyld-environment-variables-being-ignored-because-main-executable-usr-bi

**Comment by theory** [comment] 2015-09-22 20:34
Maybe? Why only some variables? Seems to happen even without `exec`. This also outputs an empty line:

    LD_LIBRARY_PATH=test bash -c 'echo $LD_LIBRARY_PATH'

**Comment by theory** [comment] 2015-09-22 20:36
Hrm. There does seem to be something in `/usr/libexec/path_helper`…

**Comment by miyagawa** [comment] 2015-09-22 20:37
So it's clearly an issue with your OS version. I cannot reproduce with OS X Yosemite btw.

**Comment by theory** [comment] 2015-09-22 20:38
Yeah, this is the El Capitan RC.

**Comment by miyagawa** [comment] 2015-09-22 20:40
There you go. Open a radar :)

**Comment by theory** [comment] 2015-09-22 20:45
I was just writing one up, in fact. Thanks.

**Comment by theory** [comment] 2015-09-22 20:50
[rdar://22807197](http://openradar.appspot.com/radar?id=4963276488179712).
