### ISSUE TITLE
Can't install Perl 5.7.2

### ISSUE THREAD

**Issue by book** [tokuhirom/plenv#116] opened 2015-12-30 08:14 UTC
After having installed `plenv`, I tried to run this:

    $ plenv install 5.7.2
    awk: fatal: cannot open file `/home/book/.plenv/version' for reading (No such file or directory)
    Installing 5.7.2 as 5.7.2
    /usr/bin/perl -- /home/book/.plenv/plugins/perl-build/bin/perl-build --symlink-devel-executables --build-dir /home/book/.plenv/build/1451459948.31245/ --tarball-dir /home/book/.plenv/cache/ -Dusedevel 5.7.2 /home/book/.plenv/versions/5.7.2
    Use the previously fetched perl-5.7.2.tar.gz
    Configuring perl '5.7.2'
    rm -f config.sh Policy.sh
    Auto-guessed '5.7.2'
    patching ext/DB_File/DB_File.xs
    patching Configure
    patching ext/IPC/SysV/SysV.xs
    File ext/IPC/SysV/SysV.xs is read-only; trying to patch anyway
    patching ext/Errno/Errno_pm.PL
    File ext/Errno/Errno_pm.PL is read-only; trying to patch anyway
    1 out of 1 hunk FAILED -- saving rejects to file ext/Errno/Errno_pm.PL.rej
    Died at /home/book/.plenv/plugins/perl-build/bin/perl-build line 17.
    ABORT

This is related to bingos/devel-patchperl#24, for which I provided a patch.

**Comment by miyagawa** [comment] 2015-12-30 08:18
How is it _related_? To me it looks like the issue is on patchperl and there's nothing to do in plenv.

**Comment by book** [comment] 2015-12-30 10:01
Indeed, the root issue is in Devel-PatchPerl. plenv merely exposes it.

If I understood correctly how plenv works (or is it build-perl?), there's a file that needs to be regenerated (fatpacked?) before the `plenv install 5.7.2` command can actually work,  once Devel-PatchPerl is fixed.

This is the reason why I opened *this* issue.

**Comment by miyagawa** [comment] 2015-12-30 14:40
Yeah it is in perl-build where Devel::PatchPerl is fatpacked. I'd recommend you to open a case in perl-build to bump the fatpack (it is a mere shell script to regenerate) once the patch in question is merged.

**Closed by miyagawa** 2015-12-30 14:40 UTC
